{% set name = "rp2paths" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: cabda6f7a94fd56dc4b8344d2482a2d7ff8e39e87e5f9a22560cab69035c4c2e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv . --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - rdkit <2024.09
    - openjdk
    - pandas
    - pydotplus
    - graphviz
    - python-graphviz
    - lxml
    - brs_utils >=1.24.0

test:
  source_files:
    - tests
  imports:
    - rp2paths
  requires:
    - python {{ python_min }}
  commands:
    - python -m rp2paths --help

about:
  home: https://github.com/brsynth/rp2paths
  summary: RetroPath2.0 to pathways
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
