{% set name = "rp2paths" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6b62bc5b256e8e541839baf675c28bcc0683bbb86b7ecd64f6705686c4a138ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - openjdk
    - rdkit =2019.03.1.0
    - pandas
    - pydotplus
    - graphviz
    - python-graphviz
    - lxml

test:
  source_files:
    - tests
  imports:
    - rp2paths
  requires:
    - pytest
  commands:
    - python -m rp2paths --help
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/rp2paths
  summary: RetroPath2.0 to pathways
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
    - kenza12
